name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  

    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npx jest

  build:

    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.1.0

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: felipemorilho/omgapi:${{github.ref_name}}

  deploy:

    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Pull Docker Image
        run: docker pull felipemorilho/omgapi:${{github.ref_name}}

      - name: Run Docker container
        run: docker run -d -p 8080:80 felipemorilho/omgapi:${{github.ref_name}}