name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: OMG
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: felipemorilho/omgapi:${{github.ref_name}}

    - name: Run Docker Compose
      run: docker-compose up -d --build